---
- name: Install ntp
  apt:
    name: ntp
    state: latest
  become: yes
  tags: [time, sudo]

- name: Configure ntp
  copy:
    src: ntp.conf
    dest: /etc/ntp.conf
  become: yes
  notify: restart ntp
  tags: [time, sudo]

- name: Set the hardware clock to UTC
  copy:
    src: adjtime
    dest: /etc/adjtime
  become: yes
  tags: [time, sudo]
