---
- name: Installes your development machine
  hosts: localhost

  roles:
    - test-sudo
    - git
    - dotfiles
    - curl
    - gnupg
    - sway
    - ntp
    - zsh
    - urxvt
    - neovim
    # - spacemacs
    - ruby
    - rust
    #    - elm
    - docker
    - htop
    - ripgrep
    - openvpn
    - awscli
    - terraform
    - psql
