- name: Create Download directory
  file:
    path: /home/{{ ansible_user_id }}/buntuble/downloads/
    state: directory
  tags: [awscli]

- name: Download awscli
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /home/{{ ansible_user_id }}/buntuble/downloads/awscli.zip
  tags: [awscli]

- name: Unzip awscli
  unarchive:
    src: /home/{{ ansible_user_id }}/buntuble/downloads/awscli.zip
    dest: /home/{{ ansible_user_id }}/buntuble/downloads/
  tags: [awscli]

- name: Install awscli
  command:
    cmd: ./install
    chdir: /home/{{ ansible_user_id }}/buntuble/downloads/aws/
    creates: /usr/local/bin/aws
  become: yes
  tags: [awscli, sudo]
