- name: Install openjdk
  ansible.builtin.apt:
    name: default-jdk
  become: true
  tags: [clojure, sudo]

- name: Install clojure
  ansible.builtin.shell: >
    curl -o- https://download.clojure.org/install/linux-install-1.11.1.1105.sh | bash
  args:
    creates: "/usr/local/bin/clojure"
  become: true
  tags: [clojure, sudo]

- name: Install rlwrap
  ansible.builtin.apt:
    name: rlwrap
  become: true
  tags: [clojure, sudo]

- name: Download Babashka
  ansible.builtin.get_url:
    url: "https://github.com/babashka/babashka/releases/download/v0.8.2/babashka-0.8.2-linux-amd64-static.tar.gz"
    dest: /home/{{ansible_user_id}}/buntuble/downloads/babashka-0.8.2-linux-amd64-static.tar.gz
  tags: [clojure]

- name: Unpack Babashka
  unarchive:
    src: /home/{{ ansible_user_id }}/buntuble/downloads/babashka-0.8.2-linux-amd64-static.tar.gz
    dest: /home/{{ ansible_user_id }}/bin
  tags: [clojure]
