---
- name: Install light-locker
  apt: name=light-locker state=latest
  become: yes
  tags: [lightlocker, sudo]

- name: Remove gnome-screensaver
  apt: name=gnome-screensaver state=absent
  become: yes
  tags: [lightlocker, sudo]
