#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"

def set_screen(screen, mode: nil, pos: nil, scale: nil)
  cmd = "swaymsg output #{screen}"
  cmd += " mode #{mode}" if mode
  cmd += " pos #{pos}" if pos
  cmd += " scale #{scale}" if scale
  system(cmd)
end

def set_keybinding(primary:, secondary:)
  system("swaymsg bindsym Mod4+w move workspace to output #{primary}")
  system("swaymsg bindsym Mod4+e move workspace to output #{secondary}")
end

outputs = JSON.parse(`swaymsg -t get_outputs`)

exit if outputs.count == 1

external_monitor = outputs.reject { |output| output["name"] == "eDP-1" }.first

if external_monitor["model"] == "U28E590"
  set_screen(external_monitor["name"], mode: "3840x2160", pos: "0 0", scale: "1.75")
  set_screen("eDP-1", pos: "960 2160")
else
  set_screen("eDP-1", pos: "0 0")
  set_screen(external_monitor["name"], pos: "1920 0")
end
set_keybinding(primary: external_monitor["name"], secondary: "eDP-1")

