---
- name: Install asdf
  ansible.builtin.shell: >
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v{{asdf_version}}
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/asdf.sh"
  tags: [asdf]

- name: Source asdf in ~/.{{ item }}
  ansible.builtin.lineinfile: >
      dest=~/.{{ item }}
      line="[ -f ~/.asdf/asdf.sh ] && . $HOME/.asdf/asdf.sh"
      create=yes
  with_items:
    - zshrc
  tags: [asdf]

- name: Install plugin dependencies
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libedit-dev
    - libssl-dev
  become: true
  tags: [asdf, sudo]

- name: Install plugins
  ansible.builtin.shell: >
    source {{ ansible_env.HOME }}/.asdf/asdf.sh && asdf plugin add {{item.plugin}} {{item.url}}
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.asdf/plugins/{{item.plugin}}/bin/install"
  with_items:
    - plugin: nodejs
      url: https://github.com/asdf-vm/asdf-nodejs.git
    - plugin: clojure
      url: https://github.com/asdf-community/asdf-clojure.git
    - plugin: java
      url: https://github.com/halcyon/asdf-java.git
    - plugin: babashka
      url: https://github.com/pitch-io/asdf-babashka.git
    - plugin: jq
      url: https://github.com/pitch-io/asdf-jq.git
    - plugin: python
      url: https://github.com/asdf-community/asdf-python

  tags: [asdf]

- name: Link ~/.tool-versions
  ansible.builtin.file:
    src: /home/{{ ansible_user_id }}/dev/files/tool-versions
    dest: /home/{{ ansible_user_id }}/.tool-versions
    state: link
  tags: [asdf]

- name: Install default tools
  ansible.builtin.shell: |
    source {{ ansible_env.HOME }}/.asdf/asdf.sh && asdf install
  args:
    executable: /bin/bash
    chdir: "$HOME"
  tags: [asdf]
