---
- name: Install Zsh
  apt:
    name: zsh
    state: latest
  become: yes
  tags: [zsh, sudo]

- name: Install better autocomplete
  ansible.builtin.git:
    repo: https://github.com/marlonrichert/zsh-autocomplete.git
    dest: /home/{{ ansible_user_id }}/buntuble/downloads/zsh-autocomplete/
  tags: [zsh]

- name: Set Zsh as default for the current user
  command: chsh -s /bin/zsh {{ ansible_user_id }}
  become: yes
  tags: [zsh, sudo]

- name: Setup /etc/zsh/zshenv
  copy:
    src: zshenv
    dest: /etc/zsh/zshenv
  become: yes
  tags: [zsh, sudo]

- name: Symlink ~/.zshrc
  file:
    src: /home/{{ ansible_user_id }}/dev/files/zshrc
    dest: /home/{{ ansible_user_id }}/.zshrc
    state: link
  tags: [zsh]
