---
- name: Install Emacs
  apt: name=emacs24 state=latest
  become: yes
  tags: [spacemacs, sudo]

- name: Install spacemacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d
  tags: [spacemacs]

- name: Link .spacemacs
  file:
    src: /home/{{ ansible_user_id }}/dev/files/spacemacs
    dest: /home/{{ ansible_user_id }}/.spacemacs
    state: link
  tags: [spacemacs]
