---
- name: Install ripgrep
  command: snap install ripgrep  --classic
  become: yes
  tags: [sudo, ripgrep]
- name: Aliasing rg
  command: snap alias ripgrep.rg rg
  become: yes
  tags: [sudo, ripgrep]
