---
- name: Ensure that git is installed
  apt:
    name: git
    state: latest
  become: true
  tags: [git, sudo]

- name: Set git config
  command: git config --global {{item.key}} "{{item.value}}"
  with_items:
    - key: user.name
      value: Johannes Barre
    - key: user.email
      value: igel@igels.net
    - key: push.default
      value: simple
    - key: commit.gpgsign
      value: true
    - key: gpg.format
      value: ssh
    - key: user.signingKey
      value: ~/.ssh/id_ed25519.pub
    - key: core.editor
      value: vi
    - key: rebase.autosquash
      value: true
    - key: pull.ff
      value: only
    - key: init.defaultBranch
      value: main
    - key: remote.origin.prune
      value: true
  tags: [git]

- name: Install gitg
  apt:
    name: gitg
    state: latest
  become: true
  tags: [git, sudo]

- name: Create Download directory
  file:
    path: /home/{{ ansible_user_id }}/buntuble/downloads/
    state: directory
  tags: [git]
