---
- name: Ensure that git is installed
  apt:
    name: git
    state: latest
  become: true
  tags: [git, sudo]

- name: Set git config
  command: git config --global {{item.key}} "{{item.value}}"
  with_items:
    - key: user.name
      value: Johannes Barre
    - key: user.email
      value: igel@igels.net
    - key: push.default
      value: simple
    - key: commit.gpgsign
      value: true
    - key: core.editor
      value: vi
    - key: rebase.autosquash
      value: true
    - key: pull.ff
      value: only
    - key: init.defaultBranch
      value: main
  tags: [git]

- name: Install gitg
  apt:
    name: gitg
    state: latest
  become: true
  tags: [git, sudo]

- name: Create Download directory
  file:
    path: /home/{{ ansible_user_id }}/buntuble/downloads/
    state: directory
  tags: [git]

- name: Install git-crypt dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - make
    - g++
    - libssl-dev
  become: true
  tags: [git, sudo]

- name: Download git-crypt
  get_url:
    url: https://github.com/AGWA/git-crypt/archive/0.6.0.tar.gz
    dest: /home/{{ ansible_user_id }}/buntuble/downloads/git-crypt.tar.gz
  tags: [git]

- name: Unpack git-crypt
  unarchive:
    src: /home/{{ ansible_user_id }}/buntuble/downloads/git-crypt.tar.gz
    dest: /home/{{ ansible_user_id }}/buntuble/downloads
  tags: [git, sudo]

- name: compile git-crypt
  command:
    cmd: make
    chdir: /home/{{ ansible_user_id }}/buntuble/downloads/git-crypt-0.6.0/
  tags: [git]

- name: Install git-crypt
  command:
    cmd: make install
    chdir: /home/{{ ansible_user_id }}/buntuble/downloads/git-crypt-0.6.0/
  become: true
  tags: [git, sudo]
