---
- name: Download chruby
  get_url:
    url: https://github.com/postmodern/chruby/archive/v{{chruby_version}}.tar.gz
    dest: /home/{{ansible_user_id}}/Downloads/chruby-{{chruby_version}}.tar.gz
  tags: [chruby]

- name: Unpack chruby
  command: /bin/tar -xzf /home/{{ansible_user_id}}/Downloads/chruby-{{chruby_version}}.tar.gz chdir=/home/{{ansible_user_id}}/Downloads/ creates=/home/{{ansible_user_id}}/Downloads/chruby-{{chruby_version}}
  tags: [chruby]

- name: Install chruby
  command: make install chdir=/home/{{ansible_user_id}}/Downloads/chruby-{{chruby_version}} creates=/usr/local/share/chruby/chruby.sh
  tags: [chruby]
  sudo: yes

- name: Setup profile.d
  tags: [chruby]
  sudo: yes
  copy: src=chruby.sh dest=/etc/profile.d/chruby.sh mode=755

- name: Setup ~/.rubies
  file: >
    dest=/home/{{ansible_user_id}}/.rubies
    state=directory
  tags: [chruby]

- name: Install required packages
  apt: name={{item}} state=latest
  sudo: yes
  with_items:
    - build-essential
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - libreadline-dev
    - libssl-dev
    - libyaml-dev
    - zlib1g-dev
  tags: [chruby]

- name: Download Ruby 2.1.5
  get_url:
    url: ftp://ftp.fu-berlin.de/unix/languages/ruby/2.1/ruby-2.1.5.tar.bz2
    dest: /home/{{ansible_user_id}}/Downloads/ruby-2.1.5.tar.bz2
    sha256sum: 0241b40f1c731cb177994a50b854fb7f18d4ad04dcefc18acc60af73046fb0a9
  tags: [chruby]

- name: Unpack Ruby 2.1.5
  command: tar xjf /home/{{ansible_user_id}}/Downloads/ruby-2.1.5.tar.bz2 chdir=/home/{{ansible_user_id}}/Downloads/ creates=/home/{{ansible_user_id}}/Downloads/ruby-2.1.5
  tags: [chruby]

- name: Install Ruby 2.1.5
  command: "{{item}} chdir=/home/{{ansible_user_id}}/Downloads/ruby-2.1.5 creates=/home/{{ansible_user_id}}/.rubies/2.1.5"
  with_items:
    - ./configure --prefix=/home/{{ansible_user_id}}/.rubies/2.1.5
    - make
    - make install
  tags: [chruby]

- name: Download Ruby 2.2.3
  get_url:
    url: ftp://ftp.fu-berlin.de/unix/languages/ruby/2.2/ruby-2.2.3.tar.xz
    dest: /home/{{ansible_user_id}}/Downloads/ruby-2.2.3.tar.xz
    sha256sum: c6ec90e9ed018e6d9a578fc93755d8565839908d5796809e1aecd1798c7ea8a7
  tags: [chruby]

- name: Unpack Ruby 2.2.3
  command: tar xJf /home/{{ansible_user_id}}/Downloads/ruby-2.2.3.tar.xz chdir=/home/{{ansible_user_id}}/Downloads/ creates=/home/{{ansible_user_id}}/Downloads/ruby-2.2.3
  tags: [chruby]

- name: Install Ruby 2.2.3
  command: "{{item}} chdir=/home/{{ansible_user_id}}/Downloads/ruby-2.2.3 creates=/home/{{ansible_user_id}}/.rubies/2.2.3"
  with_items:
    - ./configure --prefix=/home/{{ansible_user_id}}/.rubies/2.2.3
    - make
    - make install
  tags: [chruby]
