- name: Create Download directory
  file:
    path: /home/{{ ansible_user_id }}/buntuble/downloads/
    state: directory
  tags: [terraform]

- name: Create ~/bin directory
  file:
    path: /home/{{ ansible_user_id }}/bin/
    state: directory
  tags: [terraform]

- name: Download terraform
  get_url:
    url: https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
    dest: /home/{{ ansible_user_id }}/buntuble/downloads/terraform.zip
  tags: [terraform]

- name: Unpack terraform
  unarchive:
    src: /home/{{ ansible_user_id }}/buntuble/downloads/terraform.zip
    dest: /home/{{ ansible_user_id }}/bin/
  tags: [terraform]

- name: Download packer
  get_url:
    url: https://releases.hashicorp.com/packer/1.5.4/packer_1.5.4_linux_amd64.zip
    dest: /home/{{ ansible_user_id }}/buntuble/downloads/packer.zip
  tags: [terraform]

- name: Unpack packer
  unarchive:
    src: /home/{{ ansible_user_id }}/buntuble/downloads/packer.zip
    dest: /home/{{ ansible_user_id }}/bin/
  tags: [terraform]
