---
- name: Install direnv
  apt:
    name: direnv
    state: latest
  become: true
  tags: [pitch, sudo]

- name: Install python dependencies
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libxkbfile-dev
    - libbz2-dev
    - libreadline-dev
    - libssl-dev
    - libncurses5-dev
    - libsqlite3-dev
    - tk-dev
  become: true
  tags: [pitch, sudo]

- name: Install yarn
  ansible.builtin.shell: >
    source {{ ansible_env.HOME }}/.asdf/asdf.sh && npm i -g yarn
  args:
    executable: /bin/bash
    chdir: "$HOME"
  tags: [pitch]

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
  become: true
  tags: [pitch, sudo]

- name: Install yawsso
  ansible.builtin.command:
    cmd: sh -c "PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin pipx install yawsso"
  become: true
  tags: [pitch, sudo]
