---
- name: Install urxvt
  apt: name=rxvt-unicode state=latest
  become: yes
  tags: [urxvt, sudo]

- name: symlink the ~/.Xresources
  file: >
    src=/home/{{ ansible_user_id }}/dev/files/Xresources
    dest=/home/{{ ansible_user_id }}/.Xresources
    state=link
  tags: [urxvt]

- name: set urxvt as default terminal emulator
  command: update-alternatives --set x-terminal-emulator /usr/bin/urxvt
  become: yes
  tags: [urxvt, sudo]

- name: Create urxvt addon dir
  file:
    path: /usr/lib/urxvt/perl
    state: directory
  become: yes
  tags: [urxvt, sudo]

- name: Install keyboard-select
  get_url: url=https://github.com/muennich/urxvt-perls/raw/c05d319ba67c280940117d47e8f1a1ddc1b91a74/keyboard-select dest=/usr/lib/urxvt/perl/keyboard-select
  become: yes
  tags: [urxvt, sudo]

- name: Install url-select
  get_url: url=https://github.com/muennich/urxvt-perls/raw/6481d92137930291ce37c804213d9e9e6e984c3d/url-select dest=/usr/lib/urxvt/perl/url-select
  become: yes
  tags: [urxvt, sudo]

- name: Install font-size
  get_url: url=https://github.com/majutsushi/urxvt-font-size/raw/77fb033e542c48740173b2b2eb92a94149ddbc21/font-size dest=/usr/lib/urxvt/perl/font-size
  become: yes
  tags: [urxvt, sudo]

- name: Create font directory
  file:
    dest: /home/{{ansible_user_id}}/.fonts
    state: directory
  tags: [urxvt]

- name: Create Downloads directory
  file:
    dest: /home/{{ansible_user_id}}/Downloads
    state: directory
  tags: [urxvt]

- name: Download fonts
  get_url:
    url: '{{item.url}}'
    dest: /home/{{ansible_user_id}}/Downloads/{{item.name}}
  with_items:
    - url: https://github.com/be5invis/Iosevka/releases/download/v{{iosevka_version}}/01-iosevka-{{iosevka_version}}.zip
      name: iosevka.zip
    - url: https://github.com/be5invis/Iosevka/releases/download/v{{iosevka_version}}/02-iosevka-term-{{iosevka_version}}.zip
      name: iosevka-term.zip
  tags: [urxvt]

- name: Unzip fonts
  unarchive:
    src: /home/{{ansible_user_id}}/Downloads/{{item}}
    dest: /home/{{ansible_user_id}}/.fonts/
  with_items:
    - iosevka.zip
    - iosevka-term.zip
  tags: [urxvt]
  notify:
    - Refresh font cache
