---
- name: Trust Docker's signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
  become: true
  tags: [docker, sudo]

- name: Add Docker's APT sources
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    # change test to stable once that's released
    content: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic test"
  become: true
  register: sources
  tags: [docker, sudo]

- name: Update apt
  apt: update_cache=yes
  become: true
  when: sources is changed
  tags: [docker, sudo]

- name: Install Docker
  apt:
    name: docker-ce
    state: latest
  become: true
  tags: [docker, sudo]

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
  become: true
  tags: [docker, sudo]

- name: Add current user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true
  tags: [docker, sudo]
