---
- name: Trust Docker's signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 58118E89F3A912897C070ADBF76221572C52609D
  become: true
  tags: [docker, sudo]

- name: Add Docker's APT sources
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
  become: true
  register: sources
  tags: [docker, sudo]

- name: Update apt
  apt: update_cache=yes
  become: true
  when: sources|changed
  tags: [docker, sudo]

- name: Install Docker
  apt:
    name: docker-engine
    state: latest
  become: true
  tags: [docker, sudo]

- name: Install pip
  apt:
    name: python-pip
  become: true
  tags: [docker, sudo]

- name: Install Docker Compose
  pip:
    name: docker-compose
  become: true
  tags: [docker, sudo]

- name: Add current user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true
  tags: [docker, sudo]
