---
- name: Trust Docker's signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
  become: true
  tags: [docker, sudo]

- name: "Add Docker's APT sources"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu stable
    state: present
    filename: docker
  become: true
  register: sources
  tags: [docker, sudo]

- name: Install Docker
  apt:
    name: docker-ce
    state: latest
  become: true
  tags: [docker, sudo]

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
  become: true
  tags: [docker, sudo]

- name: Add current user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true
  tags: [docker, sudo]
