---
- name: Trust Docker's signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
  become: true
  tags: [docker, sudo]

- name: "Add Docker's APT sources"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu mantic stable"
    state: present
    filename: docker
  become: true
  register: sources
  tags: [docker, sudo]

- name: Install Docker
  apt:
    name: docker-ce
    state: latest
  become: true
  tags: [docker, sudo]

- name: Configure network to not collide with the Deutsche Bahn Wifi
  ansible.builtin.copy:
    content: '{"default-address-pools":[{"base":"172.30.0.0/16","size":24}]}'
    dest: /etc/docker/daemon.json
  become: true
  tags: [docker, sudo]

- name: Add current user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true
  tags: [docker, sudo]

- name: Install Docker Compose
  apt:
    name: docker-compose-plugin
    state: latest
  become: true
  tags: [docker, sudo]
