---
#- name: Install sway
#  apt:
#    name: "{{ packages }}"
#  vars:
#    packages:
#    - sway
#    - swaylock
#    - swayidle
#    - i3status
#    - mako-notifier
#  become: true
#  tags: [sway, sudo]

- name: Create .config/sway
  file:
    dest: /home/{{ ansible_user_id }}/.config/sway
    state: directory
  tags: [sway]

- name: Link .config/sway/config
  file:
    src: /home/{{ ansible_user_id }}/dev/files/sway-config
    dest: /home/{{ ansible_user_id }}/.config/sway/config
    state: link
  tags: [sway, sudo]

- name: Add user to video group so he can change the backlight brightness
  user:
    name: "{{ ansible_user_id }}"
    groups: video
    append: yes
  become: yes

- name: Configure environment variables
  copy:
    src: "{{ item }}"
    dest: /home/{{ ansible_user_id }}/.config/environment.d/{{ item }}
  with_items:
    - 10-firefox.conf
    - 10-sway.conf
    - 10-wayland.conf
  tags: [sway]

- name: Create Download directory
  file:
    path: /home/{{ ansible_user_id }}/buntuble/downloads/
    state: directory
  tags: [sway]

- name: Download bemenu
  get_url:
    url: https://github.com/Cloudef/bemenu/archive/refs/tags/0.6.3.tar.gz
    dest: /home/{{ ansible_user_id }}/buntuble/downloads/bemenu.tar.gz
  tags: [sway]

- name: Untar bemenu
  unarchive:
    src: /home/{{ ansible_user_id }}/buntuble/downloads/bemenu.tar.gz
    dest: /home/{{ ansible_user_id }}/buntuble/downloads/
  tags: [sway]

- name: Install bemenu dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - wayland-protocols
    - libwayland-bin
    - libwayland-dev
    - libcairo2-dev
    - libpango1.0-dev
    - libxkbcommon-dev
  become: true
  tags: [sway, sudo]

- name: Compile bemenu
  command:
    cmd: make clients wayland PREFIX=/usr
    chdir: /home/{{ ansible_user_id }}/buntuble/downloads/bemenu-0.6.3
  tags: [sway]

- name: Install bemenu
  command:
    cmd: make install PREFIX=/usr
    chdir: /home/{{ ansible_user_id }}/buntuble/downloads/bemenu-0.6.3
  become: true
  tags: [sway, sudo]

- name: Set cursor theme
  command: dconf write /org/gnome/desktop/interface/cursor-theme "'DMZ-Black'"
  tags: [sway]

- name: Set XDG_SESSION_TYPE=wayland
  lineinfile:
    path: /home/{{ ansible_user_id }}/.config/environment.d/10-wayland.conf
    mode: 0644
    line: XDG_SESSION_TYPE="${XDG_SESSION_TYPE:-wayland}"
    create: yes
  tags: [sway]

- name: Set XDG_CURRENT_DESKTOP=sway
  lineinfile:
    path: /home/{{ ansible_user_id }}/.config/environment.d/10-sway.conf
    mode: 0644
    line: XDG_CURRENT_DESKTOP="${XDG_CURRENT_DESKTOP:-sway}"
    create: yes
  tags: [sway]
