---
- name: Install sway
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - sway
    - swaylock
    - swayidle
    - i3status
    - mako-notifier
  become: true
  tags: [sway, sudo]

- name: Create .config/sway
  file:
    dest: /home/{{ ansible_user_id }}/.config/sway
    state: directory
  tags: [sway]

- name: Link .config/sway/config
  file:
    src: /home/{{ ansible_user_id }}/dev/files/sway-config
    dest: /home/{{ ansible_user_id }}/.config/sway/config
    state: link
  tags: [sway, sudo]

