---
- name: Install dependencies
  apt:
    pkg:
    - cmake
    - pkg-config
    - libfreetype6-dev
    - libfontconfig1-dev
    - libxcb-xfixes0-dev
    - python3
  become: yes
  tags: [alacritty, sudo]

- name: Create Download directory
  file:
    path: /home/{{ ansible_user_id }}/buntuble/downloads/
    state: directory
  tags: [alacritty]

- name: Download source
  get_url:
    url: 'https://github.com/alacritty/alacritty/archive/refs/tags/v{{ alacritty_version }}.tar.gz'
    dest: /home/{{ansible_user_id}}/buntuble/downloads/alacritty-{{ alacritty_version }}.tar.gz
  tags: [alacritty]

- name: Untar alacritty
  unarchive:
    src: /home/{{ ansible_user_id }}/buntuble/downloads/alacritty-{{ alacritty_version }}.tar.gz
    dest: /home/{{ ansible_user_id }}/buntuble/downloads/
  tags: [alacritty]

- name: Compile alacritty
  command:
    cmd: /home/{{ ansible_user_id }}/.cargo/bin/cargo build --release
    chdir: /home/{{ ansible_user_id }}/buntuble/downloads/alacritty-{{ alacritty_version }}/
    creates: /home/{{ ansible_user_id }}/buntuble/downloads/alacritty-{{ alacritty_version }}/target/release/alacritty
  tags: [alacritty]

- name: Install alacritty
  copy:
    src: /home/{{ ansible_user_id }}/buntuble/downloads/alacritty-{{ alacritty_version }}/target/release/alacritty
    dest: /usr/local/bin/alacritty
    mode: '755'
    remote_src: true
  become: yes
  tags: [alacritty, sudo]

- name: Create config directory
  file:
    dest: /home/{{ ansible_user_id }}/.local/share/applications/
    state: directory
  tags: [alacritty]

- name: Desktop config
  copy:
    src: /home/{{ ansible_user_id }}/buntuble/downloads/alacritty-{{ alacritty_version }}/extra/linux/Alacritty.desktop
    dest: /home/{{ ansible_user_id }}/.local/share/applications/Alacritty.desktop
    mode: '644'
    remote_src: true
  tags: [alacritty]

- name: Create config directory
  file:
    dest: /home/{{ansible_user_id}}/.config/alacritty/
    state: directory
  tags: [alacritty]

- name: symlink the config file
  file:
    src: /home/{{ ansible_user_id }}/dev/files/alacritty.yml
    dest: /home/{{ ansible_user_id }}/.config/alacritty/alacritty.yml
    state: link
  tags: [alacritty]

- name: set alacritty as default terminal emulator
  command: '{{ item }}'
  with_items:
    - update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/alacritty 50
    - update-alternatives --set x-terminal-emulator /usr/local/bin/alacritty
  become: yes
  tags: [alacritty, sudo]

- name: Create font directory
  file:
    dest: /home/{{ansible_user_id}}/.fonts
    state: directory
  tags: [alacritty]

- name: Download fonts
  get_url:
    url: '{{item.url}}'
    dest: /home/{{ansible_user_id}}/buntuble/downloads/{{item.name}}
  with_items:
    - url: https://github.com/be5invis/Iosevka/releases/download/v{{iosevka_version}}/super-ttc-iosevka-{{iosevka_version}}.zip
      name: iosevka.zip
  tags: [alacritty]

- name: Unzip fonts
  unarchive:
    src: /home/{{ansible_user_id}}/buntuble/downloads/{{item}}
    dest: /home/{{ansible_user_id}}/.fonts/
  with_items:
    - iosevka.zip
  tags: [alacritty]
  notify:
    - Refresh font cache
