---
- name: Install xmonad
  apt: name=xmonad state=latest
  become: yes
  tags: [xmonad, sudo]

- name: symlink the ~/.xmonad
  file: >
    src=/home/{{ ansible_user_id }}/dev/files/xmonad
    dest=/home/{{ ansible_user_id }}/.xmonad
    state=link
  tags: [xmonad]

- name: Install taffybar dependencies
  apt: name={{item}} state=latest
  with_items:
    - libxml2-dev
    - libghc-gtk-dev
    - gtk2hs-buildtools
  become: yes
  tags: [xmonad, sudo]

- name: Install cabal
  apt: name=cabal-install state=latest
  become: yes
  tags: [xmonad, sudo]

- name: Update cabal
  command: cabal update
  tags: [xmonad]

- name: Install taffybar
  command: cabal install taffybar
  tags: [xmonad]

- name: symlink ~/.config/taffybar
  file: >
    src=/home/{{ ansible_user_id }}/dev/files/taffybar
    dest=/home/{{ ansible_user_id }}/.config/taffybar
    state=link
  tags: [xmonad]

- name: Install suckless-tools for dmenu
  apt: name=suckless-tools state=latest
  become: yes
  tags: [xmonad, sudo]

- name: Install feh for background images
  apt: name=feh state=latest
  become: yes
  tags: [xmonad, sudo]

- name: symlink ~/.xinitrc
  file: >
    src=/home/{{ ansible_user_id }}/dev/files/xinitrc
    dest=/home/{{ ansible_user_id }}/.xinitrc
    state=link
  tags: [xmonad]
