---
- name: Install xmonad
  apt: name=xmonad state=latest
  sudo: yes
  tags: [sudo]

- name: symlink the ~/.xmonad
  file: >
    src=/home/{{ ansible_user_id }}/dev/files/xmonad
    dest=/home/{{ ansible_user_id }}/.xmonad
    state=link

- name: Install taffybar dependencies
  apt: name={{item}} state=latest
  with_items:
    - libxml2-dev
    - libghc-gtk-dev
  sudo: yes
  tags: [sudo]

- name: Update cabal
  command: cabal update

- name: Install taffybar
  command: cabal install taffybar

- name: Install suckless-tools for dmenu
  apt: name=suckless-tools state=latest
  sudo: yes
  tags: [sudo]
