---
- name: Install Neovim
  apt: name=neovim state=latest
  become: yes
  tags: [neovim, sudo]

- name: Setup alternatives
  alternatives: name={{item}} path=/usr/bin/nvim
  with_items:
    - vi
  become: yes
  tags: [neovim, sudo]

- name: Install xsel
  apt:
    name: xsel
    state: latest
  become: yes
  tags: [neovim, sudo]

- name: symlink the ~/.config/nvim directory
  file: >
    src=/home/{{ ansible_user_id }}/dev/files/nvim
    dest=/home/{{ ansible_user_id }}/.config/nvim
    state=link
  tags: [neovim]
