---
- name: Install lastest stable Neovim
  ansible.builtin.apt:
    deb: 'https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb'
  become: yes
  tags: [neovim, sudo]

- name: Setup alternatives
  alternatives:
    name: "{{item}}"
    path: /usr/bin/nvim
  with_items:
    - vi
  become: yes
  tags: [neovim, sudo]

- name: Install wl-clipboard
  apt:
    name: wl-clipboard
    state: latest
  become: yes
  tags: [neovim, sudo]

- name: symlink the ~/.config/nvim directory
  file:
    src: /home/{{ ansible_user_id }}/dev/files/nvim
    dest: /home/{{ ansible_user_id }}/.config/nvim
    state: link
  tags: [neovim]

- name: Make plugin directory
  file:
    dest: /home/{{ ansible_user_id }}/.local/share/nvim/site/autoload
    state: directory
  tags: [neovim]

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ ansible_user_id }}/.local/share/nvim/site/autoload/plug.vim
  tags: [neovim]

- name: vim-plug install
  command: /usr/bin/nvim -u ~/dev/files/nvim/install_vim-plug.vimrc +PlugInstall +qall
  tags: [neovim]
