---
- name: Install lastest stable Neovim
  ansible.builtin.apt:
    deb: 'https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb'
  become: yes
  tags: [neovim, sudo]

- name: Setup alternatives
  alternatives:
    name: "{{item}}"
    path: /usr/bin/nvim
  with_items:
    - vi
  become: yes
  tags: [neovim, sudo]

- name: Install wl-clipboard
  apt:
    name: wl-clipboard
    state: latest
  become: yes
  tags: [neovim, sudo]

- name: symlink the ~/.config/nvim directory
  file:
    src: /home/{{ ansible_user_id }}/dev/files/nvim
    dest: /home/{{ ansible_user_id }}/.config/nvim
    state: link
  tags: [neovim]

- name: Make plugin directory
  file:
    dest: /home/{{ ansible_user_id }}/.local/share/nvim/site/autoload
    state: directory
  tags: [neovim]

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ ansible_user_id }}/.local/share/nvim/site/autoload/plug.vim
  tags: [neovim]

- name: vim-plug install
  command: /usr/bin/nvim -u ~/dev/files/nvim/install_vim-plug.vimrc +PlugInstall +qall
  tags: [neovim]

- name: Create Download directory
  file:
    path: /home/{{ ansible_user_id }}/buntuble/downloads/
    state: directory
  tags: [neovim]

- name: Download treesitter
  get_url:
    url: https://github.com/tree-sitter/tree-sitter/releases/download/v0.20.8/tree-sitter-linux-x64.gz
    dest: /home/{{ ansible_user_id }}/buntuble/downloads/tree-sitter-linux-x64.gz
  tags: [neovim]

- name: Install treesitter
  command: sh -c "/usr/bin/gunzip /home/{{ ansible_user_id }}/buntuble/downloads/tree-sitter-linux-x64.gz -c > /usr/local/bin/tree-sitter && chmod a+x /usr/local/bin/tree-sitter"
  become: yes
  tags: [neovim, sudo]
